---
# vi: set ft=yaml.ansible :
- name: Install git
  ansible.builtin.apt:
    name: git

- name: Retrieve the repository
  ansible.builtin.git:
    depth: 1
    dest: /tmp/molecule_template
    repo: https://github.com/glacion/molecule_template
    single_branch: true
    update: false
    version: main
