---
# vi: set ft=yaml.ansible :
- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - genisoimage
      - git
      - python3
      - python3-pip
      - virtualenv
      - qemu-system-aarch64
      - qemu-system-x86
      - qemu-utils

- name: Retrieve the repository
  ansible.builtin.git:
    depth: 1
    dest: /tmp/molecule_template
    repo: https://github.com/glacion/molecule_template
    single_branch: true
    update: false
    version: main

- name: Install pip dependencies
  ansible.builtin.pip:
    chdir: /tmp/molecule_template
    requirements: requirements.txt
    virtualenv: .venv
