---
dependency:
  name: galaxy

driver:
  name: molecule-qemu

platforms:
  - name: debian-bookworm-x86_64
    image_arch: x86_64
    image_url: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2
    image_checksum: sha512:https://cloud.debian.org/images/cloud/bookworm/latest/SHA512SUMS
    network_ssh_port: 47001
    vm_cpus: 2
    vm_memory: 1024

  # - name: debian-bookworm-aarch64
  #   image_arch: aarch64
  #   image_url: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-arm64.qcow2
  #   image_checksum: sha512:https://cloud.debian.org/images/cloud/bookworm/latest/SHA512SUMS
  #   network_ssh_port: 47002

  # - name: debian-bullseye-x86_64
  #   image_arch: x86_64
  #   image_url: https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-amd64.qcow2
  #   image_checksum: sha512:https://cloud.debian.org/images/cloud/bullseye/latest/SHA512SUMS
  #   network_ssh_port: 47011

  # - name: debian-bullseye-aarch64
  #   image_arch: aarch64
  #   image_url: https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-arm64.qcow2
  #   image_checksum: sha512:https://cloud.debian.org/images/cloud/bullseye/latest/SHA512SUMS
  #   network_ssh_port: 47012

  # - name: ubuntu-jammy-amd64
  #   image_url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
  #   image_checksum: sha256:https://cloud-images.ubuntu.com/jammy/current/SHA256SUMS
  #   network_ssh_port: 47021

verifier:
  name: testinfra
  options:
    v: true
    s: true
