---
on:
  push:
    branches:
      - main

name: Molecule
run-name: Run molecule test

jobs:
  Test:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Enable KVM group permissions
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install .

      - name: Execute molecule test
        run: molecule test
