---
on:
  push:
    branches:
      - main

name: Molecule
run-name: Run molecule test

env:
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

jobs:
  Test:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up system dependencies
        run: >-
          sudo apt-get install --no-install-recommends
          qemu-system-aarch64 qemu-system-x86 mkisofs

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: pip install .

      - name: Execute molecule test
        run: molecule test
