---
on:
  push:
    branches:
      - main

name: Molecule
run-name: Run molecule test

jobs:
  Test:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: pip install .

      - name: Execute molecule test
        run: molecule test
