---
on:
  push:
    tags:
      - '*'

name: Molecule
run-name: Run molecule test

env:
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

jobs:
  Prepare:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up system dependencies
        run: >-
          sudo apt-get install --no-install-recommends
          genisoimage qemu-system-aarch64 qemu-system-x86 qemu-utils

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: pip install .

  Test:
    needs:
      - Prepare
    runs-on: ubuntu-22.04
    steps:
      - name: Execute molecule test
        run: molecule test

  Release:
    needs:
      - Test
    runs-on: ubuntu-22.04
    steps:
      - name: Publish to Galaxy
        run: >-
          ansible-galaxy role import
          --api-key ${{ secrets.GALAXY_API_KEY }}
          glacion molecule_template
