---
on:
  push:
    tags:
      - '*'
    pull_request:
      branches:
        - main

name: Release

env:
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

jobs:
  Test:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up system dependencies
        run: >-
          sudo apt-get install
          --no-install-recommends
          genisoimage qemu-system-aarch64 qemu-system-x86 qemu-utils

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: pip install .

      - name: Execute molecule test
        run: molecule test

  Release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    needs:
      - Test
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v0.1.15
        with:
          generate_release_notes: true

      - name: Publish to Galaxy
        run: >-
          ansible-galaxy role import
          --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1)
          $(echo ${{ github.repository }} | cut -d/ -f2)
